
name: CICD - Main
on:
 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-workflow-in-another-repo:
    uses: satyamdevops09/roboshop-github-actions/.github/workflows/ci-main.yml@main